event_start:
  date: "2023-11-04"
  time: "10:00"
  disable_join: true

motd_countdown: true

game_rules:
  enabled: true
  world:
    doInsomnia: false
    doFireTick: false
    doImmediateRespawn: true
    doTraderSpawning: false
    doWardenSpawning: false
    reducedDebugInfo: true
    showCoordinates: false

teams: ["schnee", "wueste", "dschungel"]

enforce_teams: true
enable_random_spawn: true

spawn_exclusion:
  max_height:
    schnee: 100
    wueste: 100
    dschungel: 100
  regions:
      - x: 8
        z: 2010
        size: 200

team_borders:
  enabled: true
  teams:
    wueste:
      x: 1792
      z: -1792
      size: 2560
    schnee:
      x: -1792
      z: -1792
      size: 2560
    dschungel:
      x: 0
      z: 1792
      size: 2560
