name: nations
version: '${version}'
main: com.itsziroy.nations.Nations
api-version: '1.20'

depend:
  - ServerTimeLock

commands:
  nation:
    permission: nations.default
    description: "Nation command"
permissions:
  nations.*:
    description: "All Nations permissions"
  nations.default:
    description: "Default permission"
    default: "op"
  nations.bypass.team_borders:
    description: "Bypass the team world borders"
    default: "op"

