name: nations
version: '${version}'
main: com.itsziroy.nations.Nations
api-version: '1.20'

depend:
  - ServerTimeLock
  - DiscordSRV

commands:
  nations:
    permission: nations.default
    description: "Nation command"
permissions:
  nations.*:
    description: "All Nations permissions"
  nations.default:
    description: "Default permission"
    default: "op"
  nations.bypass.team_borders:
    description: "Bypass the team world borders"
    default: "op"
  nations.bypass.enforce_teams:
    description: "Bypasses Team enforcement"
  nations.bypass.random_spawn:
    description: "Won't randomly spawn player on first join"
  nations.bypass.event_start:
    description: "Allows you to join even if event is not started yet."

